### ISSUE TITLE
Peer Review - Critical Assumption could be a failure mode

### ISSUE THREAD

**Issue by NateUy** [SumanyaG/Alkalytics#106]
**Artifact Under Review**
Critical Assumptions 

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Regarding the assumption: The data provided to this system is validated and correctly formatted before system ingestion. I think that it is better to have this as a potential failure mode and have the system do some input validation to make it more robust. Because in practice, there may be instances where invalid or improperly formatted data is ingested due to human error.

**Comment by SumanyaG** [comment]
See #108.
