### ISSUE TITLE
Peer Review - Inconsistencies between FMEA and Assumptions

### ISSUE THREAD

**Issue by NateUy** [SumanyaG/Alkalytics#107]
**Artifact Under Review**
FMEA table and Critical Assumptions

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
It is noted in the assumptions section that "Internet connection and server infrastructure will always be available, and will not suddenly go down and compromise the system" But in the causes of failure column of the FMEA table, specifically in the DB connection lost row, it states, "Network issues, server downtime" So I think there is an inconsistency here.

**Comment by SumanyaG** [comment]
We will update the critical assumption to only include the availability of the local server infrastructure.

**Comment by JenniferYe25** [comment]
Thank you for the catch! Updated in the following commit: https://github.com/SumanyaG/Alkalytics/commit/a5ac645fa18e5a2489d0221ee6a1acee6efda7a4
