### ISSUE TITLE
Peer Review - Unnecessary Assumption 

### ISSUE THREAD

**Issue by Declan-Young** [SumanyaG/Alkalytics#108]
**Artifact Under Review**
Hazard Analysis

- 4 - Critical Assumptions
- 5 - Failure Mode and Effect Analysis

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
One of the assumptions listed is that data is validated before it is ingested into the system. I am wondering if this is a necessary assumption to make, as one of the recommended actions in the Failure Mode and Effect Analysis is to improve input data validation. I think this recommended action should be changed if the the system is going to assume all data is validated prior to ingestion, otherwise the assumption can probably be removed instead, as the system will be doing the validation.

**Comment by SumanyaG** [comment]
We will remove the critical assumption to ensure consistency with the FMEA.

**Comment by JenniferYe25** [comment]
Thank you for the catch! Updated in the following commit: https://github.com/SumanyaG/Alkalytics/commit/a5ac645fa18e5a2489d0221ee6a1acee6efda7a4
