### ISSUE TITLE
Peer Review - Unnecessary Requirement

### ISSUE THREAD

**Issue by Declan-Young** [SumanyaG/Alkalytics#109]
**Artifact Under Review**
Hazard Analysis

- 4 - Critical Assumptions
- 6.5 - Immunity Requirements

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
One of the assumptions listed is that the system will have enough resources for any amount of data. However, requirement SR-17 states that there must be monitoring and optimization of resources to prevent crashes from too many resources being used. I think that this requirement is not necessary since it is assumed that there always be enough resources available for the system.

**Comment by SumanyaG** [comment]
We will remove this assumption to be consistent with the requirements.

**Comment by JenniferYe25** [comment]
Thank you for the catch! Updated in the following commit: https://github.com/SumanyaG/Alkalytics/commit/a5ac645fa18e5a2489d0221ee6a1acee6efda7a4
