### ISSUE TITLE
Peer Review - Assumption Quality

### ISSUE THREAD

**Issue by AidanMariglia** [SumanyaG/Alkalytics#110]
**Artifact Under Review**
Hazard analysis 

4 Critical Assumptions

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
The assumption is made "Internet connection and server infrastructure will always be available, and will not suddenly go down and compromise the system". I think this is a bad assumption to make, as real world experience shows this is almost never true. By making this assumption, we fail to consider the consequences of connection/server failures, and do not make use any techniques to mediate these failures, resulting in an overall less reliable/robust system. Removing this assumption, and instead considering how the system needs to behave in the case of a server reboot, network blip etc. may be a good decision.

**Comment by SumanyaG** [comment]
See #107.
