### ISSUE TITLE
Peer Review - Test For Nonfunctional Requirement Is Not Very Specific

### ISSUE THREAD

**Issue by Declan-Young** [SumanyaG/Alkalytics#136]
**Artifact Under Review**
Verification and Validation Plan

- 4.2.1 - Look and Feel Requirements
  - NFR-LF2 

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
I think it would be beneficial to make the NFR-LF2 test for the requirement LF2 (Device Compatibility) more specific, by mentioning specifically what devices will used to test device compatibility (mobile device/laptop, display size, etc.)

**Comment by JenniferYe25** [comment]
Edits have been pushed in this commit: https://github.com/SumanyaG/Alkalytics/commit/3bdb4be349c6e2862f4c7662d632b4d40dd5c667
