### ISSUE TITLE
Peer Review - Test For Functional Requirement Is Not Very Specific

### ISSUE THREAD

**Issue by Declan-Young** [SumanyaG/Alkalytics#137]
**Artifact Under Review**
Verification and Validation Plan

- 4.1.1 - Data Input and Storage
  - FR-ST1

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Since the test FR-ST1 corresponds to 4 different Functional Requirements (FR-1, FR-2, FR-3 and FR-4), I think it would be better to split this test in to two, more specific, tests. For example, the test currently uses a CSV file as input, which makes sense for FR-3, however it this test may not be specific enough to cover FR-1 which requires the system to allow users to input new data and parameters.

**Comment by JenniferYe25** [comment]
Edits have been pushed in this commit: https://github.com/SumanyaG/Alkalytics/commit/3bdb4be349c6e2862f4c7662d632b4d40dd5c667
