### ISSUE TITLE
Peer Review - functional requirement test, unclear output

### ISSUE THREAD

**Issue by AidanMariglia** [SumanyaG/Alkalytics#138]
**Artifact Under Review**
Verification and Validation Plan

4.1 Tests for functional requirements
4.1.1 Data input and storage
FR-ST1

**Team Number for Team Doing the Review**
1

**Description of Issue**
The specified output of this test is "Data that is inputted is sent into the system, then labelled and stored successfully". This is not really an output, but rather a process that is supposed to happen. What output would be returned to indicate this process was successful?

**Comment by SumanyaG** [comment]
We will update the output and replace the current statement with something along the lines of "The inputted data is stored in the system with proper labels and without any data loss or errors".

**Comment by JenniferYe25** [comment]
Edits have been pushed in this commit: https://github.com/SumanyaG/Alkalytics/commit/3bdb4be349c6e2862f4c7662d632b4d40dd5c667
