### ISSUE TITLE
Peer Review - Lack of Automated functional tests

### ISSUE THREAD

**Issue by AidanMariglia** [SumanyaG/Alkalytics#139]
**Artifact Under Review**
Verification and Validation Plan
4.1 Tests for functional requirements

**Team Number for Team Doing the Review**
1

**Description of Issue**
All of the tests for functional requirements are manual. Automated tests have higher initial costs as they require some development work but have higher value throughout the life of a project, as they can be periodically run to ensure that none of the key functions of the system have been broken by changes. Consider adding more Automated tests for your functional requirements.

**Comment by SumanyaG** [comment]
Since most of the tests for the FRs are pretty uncomplicated, manual tests made more sense and outweighed the initial costs of the automated tests. Agreed on the repetitive use of the automated tests, though. We will keep automated tests in mind when planning further testing, though.
