### ISSUE TITLE
Peer Review - Lack of functional tests for incorrect inputs

### ISSUE THREAD

**Issue by BenDubi** [SumanyaG/Alkalytics#141]
**Artifact Under Review**
Verification and Validation Plan
4.1 Tests for Functional Requirements
4.1.5 User Access

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
For the user access tests, there is currently one test that ensures valid credentials work on the system and allow the user to log in, however, there is no test for ensuring the system safely handles the scenario where incorrect credentials are provided. This should be tested as well to ensure invalid inputs do not cause fatal errors.

**Comment by SumanyaG** [comment]
All possible scenarios related to authentication have been covered under NFR-SR1.
