### ISSUE TITLE
Supervisor Meeting - 18/12/2024

### ISSUE THREAD

**Issue by JenniferYe25** [SumanyaG/Alkalytics#164]
**18/12/24 @ 11:30am**

**Attendance**
- [x] Bassel Abdulkader
- [ ] Dr. Charles de Lannoy
- [x] Sumanya Gulati
- [x] Kate Min
- [x] Jennifer Ye
- [x] Jason Tran

**Agenda**
- Present project review
- https://mcmasteru365-my.sharepoint.com/:p:/r/personal/yej52_mcmaster_ca/_layouts/15/Doc.aspx?sourcedoc=%7B65043C53-A7D0-4F91-BBA5-F04806D6CDF6%7D&file=Alkalytics%20Fall%20Semester%20Progress%25u200b.pptx&action=edit&mobileredirect=true 

**Questions to Ask**
-

**Comment by SumanyaG** [comment]
Meeting Minutes:
- Jennifer went through the presentation (attached in the agenda).
- Bassel inquired about Rev 0 demo and what will be included in it.
- Bassel will be leaving in a month so include Meghna and Dr. de Lannoy in winter check-ins.
- Check in with the supervisors second week of January.
- Jennifer will email slide deck to everyone.
