### ISSUE TITLE
SRS - 2 Stakeholders

### ISSUE THREAD

**Issue by JenniferYe25** [SumanyaG/Alkalytics#82]

**Comment by jsontran** [comment]
2.2) people can get -> that can be obtained.
2.1 & 2.2 & 2.3) Add transitional words, in addition, futheremore, etc
2.4) Technological? Technical makes more sense
2.3 & 2.6.1) Student -> Student Assistant

2.8) put a label on 2.4 so we can click on it
2.8) research time -> research team
