### ISSUE TITLE
SRS - 10 Look and Feel Requirements

### ISSUE THREAD

**Issue by JenniferYe25** [SumanyaG/Alkalytics#83]

**Comment by jsontran** [comment]
- Add rationale to your requirements
- There are spelling errors
LFR-5) Artistic style is too ambigious, say follows a design standard
10.2) instead of saying after a user's first encounter, just say that the application should (not) ...
 like should have consistent fonts throughout the application

**Comment by JenniferYe25** [comment]
@jsontran I find that rational for this section will all be the same. It would be a bit counter productive
