### ISSUE TITLE
Peer Review - Missing stakeholder

### ISSUE THREAD

**Issue by NateUy** [SumanyaG/Alkalytics#88]
**Artifact Under Review**
Stakeholders - 2.3 Other stakeholders

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Developers/Testers are considered other stakeholders according to the Volere template as they have the technical knowledge that influences how requirements can be implemented. Their inputs will shape the solution based on available technologies.

**Comment by SumanyaG** [comment]
While I agree that the Volere template considers developers and testers as stakeholders (albeit different from end-users), I remember either the professor or the TA mentioning we shouldn't include them as stakeholders for the SRS. Thanks for flagging this and we will look into it!
