### ISSUE TITLE
Peer Review - Missing Customer

### ISSUE THREAD

**Issue by AidanMariglia** [SumanyaG/Alkalytics#89]
**Artifact Under Review**
Stakeholders - 2.2 Customer

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Following the Volere template guidance, for in house development the customer and client are often the same person. In this case while other customers may be a future goal, the initial customer would be the client.

**Comment by JenniferYe25** [comment]
Thank you for the catch. Updated on the SRS branch 
https://github.com/SumanyaG/Alkalytics/commit/5489e4f70eb767b0e9e46981b3d7e12537bcce78
