### ISSUE TITLE
Peer Review - Missing Business Process Models

### ISSUE THREAD

**Issue by AidanMariglia** [SumanyaG/Alkalytics#90]
**Artifact Under Review**
The Scope of Work - 6.1 The current situation

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Lack of business process models as suggested in the volere template guidance. These models identify existing roles, individuals, departments, technology and procedures, and their relationships.

**Comment by SumanyaG** [comment]
Section 6.2 with the Work Context Model identifies existing roles, individuals and their relationships.
