### ISSUE TITLE
Peer Review - Inconsistency between requirements

### ISSUE THREAD

**Issue by Declan-Young** [SumanyaG/Alkalytics#91]
**Artifact Under Review**
SRS - Usability and humanity requirements

- 11.1 - Ease of use requirements
- 11.3 - Learning requirements

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Since the requirements UHR-1 (11.1 - Ease of use requirements) and UHR-4 (11.3 - Learning requirements) are very closely related (they both describe that a user should be able to easily use/navigate the application with minimal training), I think that the requirements should specify the same percentage of users. However, currently UHR-1 specifies 90% of users, while UHR-4 specifies 85% of users.

**Comment by SumanyaG** [comment]
Thanks for catching that. We'll fix it right away!

**Comment by SumanyaG** [comment]
Changed UHR-1 percentage to 85% to ensure consistency with UHR-4.
