### ISSUE TITLE
Peer Review - Requirement that is not verifiable 

### ISSUE THREAD

**Issue by Declan-Young** [SumanyaG/Alkalytics#92]
**Artifact Under Review**
SRS - Operational and Environmental Requirements
- 13.4 - Productization Requirements

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Requirement OER-5 states that the application's onboarding process should be easy. However, since this is quite subjective (what is an easy process to one person may be difficult to another), it would probably be good to change this requirement to have a measure of what makes an onboarding process easy, so that it is verifiable.

**Comment by SumanyaG** [comment]
We will tie this back to UHR-1 and UHR-4. We can include the same testing percentage (85%) to ensure consistency. Thanks for spotting that!

**Comment by katemin991** [comment]
feedback addressed in commit c788b05c818ec1699c85fbcf4c1393918d096605
