### ISSUE TITLE
Peer Review - Inputs and Outputs Missing In Use Case Diagram

### ISSUE THREAD

**Issue by BenDubi** [SumanyaG/Alkalytics#93]
**Artifact Under Review**
SRS - The Scope of the Product

- 8.1 - Product Boundary

**Team Number for Team Doing the Review**
Team 1

**Description of Issue**
Following the Voltere template guidance, it is suggested that the inputs and outputs of each product use case be displayed on the product use case diagram. Currently, the inputs and outputs are outlined in the Product Use Case Table but are not found in the diagram. Instead of the inputs and outputs as the connections of the diagram, you currently have the user motivation for the use case.

**Comment by JenniferYe25** [comment]
Use case diagrams are not suppose to include explicit inputs and outputs. Use case diagrams should only show the actors, use case, boundaries and relationships. For something like a class diagrams inputs and outputs will be needed. If you could specify or give an example of a use case that has inputs and outputs, that would greatly help. 

This issue will be closed until further notice
